name: PINK MIST
favicon: null
layout_spectrum: 0.12543784570880234
typography_spectrum: 0.2054106646683067
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.2828617540653795
  lightness: 0.615033203503117
  saturation: 0.3530727280303836
  rhythmicContrast: 0.5977861366700381
purpose: []
